"""add_tenant_id_to_orders

Revision ID: 21ce55d841b4
Revises: 8b41ba924288
Create Date: 2026-03-19 23:22:02.244993

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ce55d841b4'
down_revision: Union[str, None] = '8b41ba924288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
