"""Postgres Init

Revision ID: 8b41ba924288
Revises: 
Create Date: 2026-03-19 12:04:21.223271

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b41ba924288'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('orders', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'])
    op.add_column('pacotes', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pacotes_tenant_id'), 'pacotes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'pacotes', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.add_column('webhook_events', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_webhook_events_tenant_id'), 'webhook_events', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'webhook_events', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_index(op.f('ix_webhook_events_tenant_id'), table_name='webhook_events')
    op.drop_column('webhook_events', 'tenant_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'pacotes', type_='foreignkey')
    op.drop_index(op.f('ix_pacotes_tenant_id'), table_name='pacotes')
    op.drop_column('pacotes', 'tenant_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_column('orders', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
